[book]
authors = ["Foo Yong Qi"]
language = "en"
multilingual = false
src = "src"
title = "Typed Functional Programming"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
mathjax-support = true
additional-css = ["custom.css"]
